name: Hello GitHub Actions

on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Repo
        run: |
          echo "Repo: ${{ github.repository }}"

      - name: Branch
        run: |
          echo "Branch: ${{ github.ref_name }}"

      - name: Date
        run: date
