name: Hello GitHub Actions

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository
        run: echo "Repo: ${{ github.repository }}"

      - name: Print branch
        run: echo "Branch: ${{ github.ref_name }}"

      - name: Print date
        run: date
